//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandbox.Blazor.Components.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Weather_razor {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Weather_razor() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sandbox.Blazor.Components.Pages.Weather_razor", typeof(Weather_razor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string CelciusHeader {
            get {
                return ResourceManager.GetString("CelciusHeader", resourceCulture);
            }
        }
        
        internal static string CelciusDescription {
            get {
                return ResourceManager.GetString("CelciusDescription", resourceCulture);
            }
        }
        
        internal static string FahrenheitDescription {
            get {
                return ResourceManager.GetString("FahrenheitDescription", resourceCulture);
            }
        }
        
        internal static string FahrenheitHeader {
            get {
                return ResourceManager.GetString("FahrenheitHeader", resourceCulture);
            }
        }
        
        internal static string DateHeader {
            get {
                return ResourceManager.GetString("DateHeader", resourceCulture);
            }
        }
        
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        internal static string Cool {
            get {
                return ResourceManager.GetString("Cool", resourceCulture);
            }
        }
        
        internal static string SwitchToEnglish {
            get {
                return ResourceManager.GetString("SwitchToEnglish", resourceCulture);
            }
        }
    }
}
