// <auto-generated />
using LasseVK.Jobs.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LasseVK.Jobs.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20250202122122_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobEntityJobEntity", b =>
                {
                    b.Property<string>("DependsOnId")
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DependsOnMeId")
                        .HasColumnType("character varying(32)");

                    b.HasKey("DependsOnId", "DependsOnMeId");

                    b.HasIndex("DependsOnMeId");

                    b.ToTable("JobEntityJobEntity");
                });

            modelBuilder.Entity("LasseVK.Jobs.PostgreSQL.JobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("Group")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identifier");

                    b.Property<string>("JobJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("JobEntityJobEntity", b =>
                {
                    b.HasOne("LasseVK.Jobs.PostgreSQL.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LasseVK.Jobs.PostgreSQL.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("DependsOnMeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
