// <auto-generated />
using System;
using LasseVK.Jobs.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LasseVK.Jobs.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LasseVK.Jobs.PostgreSQL.JobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<string>("Group")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WhenCompleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset>("WhenQueued")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued");

                    b.Property<DateTimeOffset?>("WhenStarted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started");

                    b.HasKey("Id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("LasseVK.Jobs.PostgreSQL.JobLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("log");

                    b.Property<DateTimeOffset>("WhenLogged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("when");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "JobId" }, "logs_job_id");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("dependencies", b =>
                {
                    b.Property<string>("dependencyId")
                        .HasColumnType("character varying(32)");

                    b.Property<string>("dependentId")
                        .HasColumnType("character varying(32)");

                    b.HasKey("dependencyId", "dependentId");

                    b.HasIndex("dependentId");

                    b.ToTable("dependencies");
                });

            modelBuilder.Entity("LasseVK.Jobs.PostgreSQL.JobLogEntity", b =>
                {
                    b.HasOne("LasseVK.Jobs.PostgreSQL.JobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("dependencies", b =>
                {
                    b.HasOne("LasseVK.Jobs.PostgreSQL.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("dependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LasseVK.Jobs.PostgreSQL.JobEntity", null)
                        .WithMany()
                        .HasForeignKey("dependentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
